inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - "*.gemspec"
    - Rakefile
    - "**/*.rake"
    - spec/**/*.rb

Metrics/MethodLength:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/IndentHeredoc:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/WordArray:
  EnforcedStyle: brackets

RSpec/ExampleLength:
  Enabled: false
