inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

RSpec/ExampleLength:
  Enabled: false

Layout/IndentHeredoc:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - "*.gemspec"
    - Rakefile
    - "**/*.rake"
    - spec/**/*.rb
