sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2

before_install: gem install bundler -v 1.16.0

script:
  - bundle exec rspec
  - bundle exec rubocop

notifications:
  email: false
